version: '3.4'
services:    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '${ROOT}/config/prowlarr:/config'
    restart: unless-stopped
    ports:
      - '9696:9696'

  sonarr:
    container_name: sonarr
    image: 'linuxserver/sonarr:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${LOCALSTORAGE}/config/sonarr:/config'
      - '${NASSTORAGE}:/downloads'
  radarr:
    container_name: radarr
    image: 'linuxserver/radarr:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${LOCALSTORAGE}/config/radarr:/config'
      - '${NASSTORAGE}:/downloads'
      
  bazarr:
    container_name: bazarr
    image: 'linuxserver/bazarr:latest'
    restart: unless-stopped
    #network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
      - UMASK_SET=022
    volumes:
      - '${LOCALSTORAGE}/config/bazarr:/config'
      - '${NASSTORAGE}:/downloads'
    ports:
      - '6767:6767'
      
  seerr:
    image: 'ghcr.io/seerr-team/seerr:latest'
    init: true
    container_name: seerr
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - LOG_LEVEL=debug
      - 'TZ=${TZ}'
      - PORT=5055
    ports:
      - '5055:5055'
    volumes:
      - '${LOCALSTORAGE}/config/seerr/config:/app/config'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
